services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: mysql_practicascabildo
    volumes:
      - ./db_data:/var/lib/mysql
    user: "1000:1000"